### Create the shorten url
POST http://localhost:3000/urls/
Content-Type: application/json

{
    "originalUrl": "https://github.com/TLBTrung-222/ecommerce-mern/blob/main/server/src/types/common/Response.type.ts"
}

### Get the original url
GET http://localhost:3000/urls/909576
